### ISSUE TITLE
auto liquidity and and reward add functionality is not working

### ISSUE THREAD

**Issue by Usman-47** [FreezyEx/Deflationary-Token#10]
when i make any transaction auto liquidity add AND auto reward function is not working. can you please elaborate how these functionality will work. or there is any function that i have to called to provide the reward to holders.

**Comment by FreezyEx** [comment]
Can you provide a link to the contract?

Il giorno lun 6 dic 2021 alle ore 15:02 Usman-47 ***@***.***>
ha scritto:

**Comment by Usman-47** [comment]
Here is the link to my contract: https://testnet.bscscan.com/address/0xB5F479B8C602A03bFdBc88Be08aB91F73593a825

**Comment by FreezyEx** [comment]
from what I see you didn't add liquidity yet

Il giorno lun 6 dic 2021 alle ore 20:29 Usman-47 ***@***.***>
ha scritto:

**Comment by Usman-47** [comment]
now i have added liquidity, but auto liquidity and auto reward on every transaction is not working, may i have to run any specific function to make auto reward working?

**Comment by FreezyEx** [comment]
Are you using this to add liquidity?
https://pancake.kiemtienonline360.com/#/swap

If yes then please redeploy using this router address:
https://testnet.bscscan.com/address/0x9ac64cc6e4415144c455bd8e4837fea55603e5c3

Also take in mind the code is "old", it can be improved and upgraded. I
just leave it as it is due to is one of my firsts codes. Please don't
hesitate to change ti

Il giorno mar 7 dic 2021 alle ore 08:16 Usman-47 ***@***.***>
ha scritto:

**Comment by PnW1** [comment]
I have tried adding liquidity with https://pancake.kiemtienonline360.com/#/swap

and also, I have deployed a new contract using https://testnet.bscscan.com/address/0x9ac64cc6e4415144c455bd8e4837fea55603e5c3 router address... when I use this router address I can add liquidity but am unable to swap..

However, I have worked with the default router address that was previously added, I can swap and add liquidity manually, But unable to get reward and addition of auto liquidity.... 
![image](https://user-images.githubusercontent.com/70314412/145004839-a59a6d9a-6f31-4c19-92c0-c74cba5a1765.png)

**Comment by Usman-47** [comment]
I have tried adding liquidity with https://pancake.kiemtienonline360.com/#/swap

and also, I have deployed new contract using https://testnet.bscscan.com/address/0x9ac64cc6e4415144c455bd8e4837fea55603e5c3 router address... when I use this router address I can add liquidity but unable to swap..

However, I have worked with default router address that was previously added, I can swap and add liquidity manually, But unable to get reward and addition of auto liquidity.... 
![image](https://user-images.githubusercontent.com/81434988/145005191-ec5a6fa4-b39d-4733-9b2b-f6b79b415db3.png)

**Comment by Usman-47** [comment]
please check, here is the contract with suggested router address: https://testnet.bscscan.com/address/0x8Fb70C616cA581B75801CDD087f7052f55409e56#readContract

**Comment by Usman-47** [comment]
when i use this router address(0xD99D1c33F9fC3444f8101754aBC46c52416550D1) with your provide swap link then its add liquidity and swap liquidity does work

**Comment by Usman-47** [comment]
but reward reflection and auto liquidity on every transaction is still not working

**Comment by FreezyEx** [comment]
sorry how are you checking reflection? You won't see any transaction for it.
Also please can you try to force a normal transfer between EOA and send the
tx?


Il giorno mar 7 dic 2021 alle ore 11:07 Usman-47 ***@***.***>
ha scritto:

**Comment by Usman-47** [comment]
what is meant by EOA? i also try transfer from metamask to another metamask account. burn fee and charity are deducted, reflection are also deducted. but when check the holder, it remain the same.
![image](https://user-images.githubusercontent.com/81434988/145018541-177d041d-4222-4a80-94fa-212499285495.png)

**Comment by Usman-47** [comment]
is it possible to contact you on skype?

**Comment by FreezyEx** [comment]
No sorry , if you can pm me on telegram
@FreezyDev

Il giorno mar 7 dic 2021 alle ore 12:11 Usman-47 ***@***.***>
ha scritto:

**Comment by Usman-47** [comment]
I am very glad that you helped me.such a nice person, help me a lot, thank you Freezy, to be a nice person

**Comment by Ququlqan** [comment]
@Usman-47 hi Usman, 
did you solve the issue? Is the code now working 100%
I tried the code and have similar issues like you.
Could I kindly ask you for yours?

Br

**Comment by Usman-47** [comment]
yes i had solve the issue. freezy helped me to solve my issue
